### ISSUE TITLE
DynamoDB backups are off (High)

### ISSUE THREAD

**Issue by arkadiyg** [gobranch/appsync-third-party-gateway#2]
Find more live information in Aikido here: https://app.aikido.dev/queue?sidebarIssue=173228&groupId=1273&sidebarIssueTask=13117&sidebarTab=tasks

==== Scope ====
This task includes issues in the following code repository:
- branch

==== TLDR ====
DynamoDB is running without automated backups. Point-in-time recovery recovery can help you recover from accidental write or delete operations.

==== How to fix ====
Enable point-in-time recovery for DynamoDB in IaC
To declare this entity in your AWS CloudFormation template, use the following syntax:

JSON

{
  "PointInTimeRecoveryEnabled" : Boolean
}

YAML

  PointInTimeRecoveryEnabled: Boolean

**Comment by dabrunetti** [comment]
Attn @iherndon

**Comment by tallpants** [comment]
@dabrunetti @arkadiyg this is a public repo that we made as an example -- nothing here is actually running in production (or anywhere else). No point having Aikido scanning this (and other repos in the org that don't have any code that's being used in any way).
